/**
 * ProcessSection — "HOW THIS SITE IS BUILT".
 *
 * Server component: static copy, no state, no effects.
 *
 * HONESTY NOTE — read before editing the check rows below.
 * The four numbered steps describe the *intended* pipeline. The CHECKS panel
 * describes what is actually enforced today, and nothing more. Rows marked
 * `pending` are aspirational, and their values are stated as targets, never as
 * measurements. Do not put a KB figure or a draw-call count in a `pending`
 * row — flip it to `passing` and fill in the real number only once something
 * actually prints one.
 *
 * Two rows were flipped when the Blender pipeline landed:
 *   - `hero.glb` size is printed by `npm run hero:check`, which the
 *     `asset-budget` job in `.github/workflows/ci.yml` runs on every push and
 *     PR against the committed asset.
 *   - draw calls per frame were measured in a browser, by a Playwright probe
 *     counting `drawArrays*`/`drawElements*` on the WebGL2 prototype across a
 *     sampling window, idle and mid-scroll. CI does NOT measure this: the
 *     budget script can only prove the asset *permits* one draw call (112
 *     nodes, one shared mesh, one shared material), never that the scene
 *     honours it. That distinction is what `note` exists to carry — do not
 *     drop it to tidy the row up.
 */

type CheckStatus = 'passing' | 'pending';

interface PreviewCheck {
  /** What is being checked. */
  name: string;
  /** The result today, or the budget it is aiming at if still pending. */
  value: string;
  status: CheckStatus;
  /** Where a figure came from, when that is not "a job in this pipeline". */
  note?: string;
}

/**
 * Every row below maps to a real step in `.github/workflows/ci.yml`, to a
 * measurement taken outside it (and labelled as such), or to a step that does
 * not exist yet (pending).
 */
const PREVIEW_CHECKS: PreviewCheck[] = [
  // --- Enforced today, on every pull request. ---------------------------
  { name: 'lint', value: 'npm run lint', status: 'passing' },
  { name: 'unit tests', value: 'npm run test:unit', status: 'passing' },
  { name: 'production build', value: 'npm run build', status: 'passing' },
  { name: 'end-to-end + visual snapshots', value: 'npm run test:e2e', status: 'passing' },
  { name: 'hero.glb size', value: '8.5 KB of 500 KB budget', status: 'passing' },

  // --- Real, but measured in a browser rather than by a CI job. ---------
  {
    name: 'draw calls per frame',
    value: '1.00 of 10 budget',
    status: 'passing',
    note: 'measured in-browser, idle and mid-scroll — not a CI job',
  },

  // --- Aspirational: nothing has measured this yet. ---------------------
  { name: 'mid-range phone', value: 'not yet tested', status: 'pending' },
];

interface ProcessStep {
  title: string;
  line: string;
}

const STEPS: ProcessStep[] = [
  { title: 'Design', line: 'Sketch each section and what the blocks should do there.' },
  { title: 'Build in Blender', line: 'A Python script generates the blocks and exports hero.glb.' },
  {
    title: 'Animate on the web',
    line: 'React Three Fiber moves the parts on scroll, with a still-image fallback.',
  },
  {
    title: 'Verify',
    line: 'Playwright captures each section; budgets guard file size and draw calls.',
  },
];

/** The mockup fills the second badge. Purely decorative emphasis — the circle
 *  is aria-hidden, so it never claims that step is "done" to a screen reader;
 *  the surrounding <ol> carries the real numbering. */
const FILLED_STEP_INDEX = 1;

/* Panel palette. These two values are scoped to the dark checks panel only:
   #161310 is the `ink` token used as a surface, #EDE8DA is its paper-toned
   text (14.99:1). `lime` and `cta` appear here as the pass/pending marks —
   6.00:1 and 13.76:1 on this surface — which is the one place the section spec
   calls for them outside their usual one-job contract. */
const PANEL_TEXT = 'text-[#EDE8DA]';

export function ProcessSection() {
  return (
    <section id="process" className="w-full py-20 md:py-28">
      <div className="mx-auto w-full max-w-5xl px-6 md:px-10">
        <p className="eyebrow">HOW THIS SITE IS BUILT</p>

        <h2 className="mt-5 max-w-[18ch] font-display text-[32px] leading-[1.05] md:text-[52px]">
          The background is a Blender file.
        </h2>

        <p className="mt-6 max-w-[62ch] text-base leading-relaxed text-body">
          Each block is a named part with its own pivot, generated by a Python script. The page
          moves those parts as you scroll, and every preview deploy checks them against a budget.
        </p>

        <ol className="mt-12 grid gap-7 md:mt-14">
          {STEPS.map((step, index) => (
            <li key={step.title} className="grid grid-cols-[30px_1fr] items-start gap-x-4">
              <span
                aria-hidden="true"
                className={`flex h-[30px] w-[30px] items-center justify-center rounded-pill border border-ink font-mono text-xs font-bold leading-none ${
                  index === FILLED_STEP_INDEX ? 'bg-lime text-lime-ink' : 'bg-surface text-ink'
                }`}
              >
                {index + 1}
              </span>
              <div className="pt-1">
                <h3 className="font-display text-lg leading-tight text-ink">{step.title}</h3>
                <p className="mt-1.5 max-w-[58ch] text-[15px] leading-relaxed text-body-soft">
                  {step.line}
                </p>
              </div>
            </li>
          ))}
        </ol>

        {/* --- What CI actually runs ---------------------------------- */}
        <div className={`mt-12 rounded-md bg-ink p-5 md:mt-14 md:p-6 ${PANEL_TEXT}`}>
          <div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-2 font-mono text-[11.5px] uppercase leading-5 tracking-[0.12em]">
            <span className="font-bold text-lime">Checks on every preview</span>
            <span className={PANEL_TEXT}>GitHub Actions</span>
          </div>

          <ul className="mt-4 font-mono text-[11.5px] leading-5">
            {PREVIEW_CHECKS.map((check) => {
              const passing = check.status === 'passing';

              return (
                <li
                  key={check.name}
                  className="grid grid-cols-[1rem_1fr] items-baseline gap-x-3 gap-y-0.5 border-t border-[#EDE8DA]/15 py-2 sm:grid-cols-[1rem_1fr_auto]"
                >
                  <span
                    aria-hidden="true"
                    className={passing ? 'text-lime' : 'text-cta'}
                  >
                    {passing ? '✓' : '✗'}
                  </span>
                  <span className={PANEL_TEXT}>
                    {check.name}
                    <span className="sr-only">{passing ? ' — passing' : ' — pending'}</span>
                    {check.note ? (
                      <span className="block text-[10.5px] leading-4 text-[#EDE8DA]/55">
                        {check.note}
                      </span>
                    ) : null}
                  </span>
                  <span
                    className={`col-start-2 sm:col-start-3 sm:text-right ${
                      passing ? 'text-[#EDE8DA]/70' : 'text-cta'
                    }`}
                  >
                    {check.value}
                  </span>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    </section>
  );
}
