import { CORPUS, type Corpus, type Evidence } from '@/data/corpus';

import type { FitReport, Requirement, Verdict } from './contract';
import { entryLabel, evidenceLabel } from './labels';
import { levelLine } from './level';
import { SCAN_DISCLAIMER } from './scan';

/**
 * "COPY AS MARKDOWN" — the report as plain text a recruiter can paste into
 * an email, a doc or an ATS note. Pure string building: no HTML, and every
 * piece of text that came from the JD (role, requirement text, skill names)
 * has Markdown syntax escaped, so a pasted JD can't smuggle in a link.
 */

export const VERDICT_LABELS: Readonly<Record<Verdict, string>> = {
  strong: 'Strong',
  partial: 'Partial',
  gap: 'Gap',
  not_assessed: 'Not assessed',
};

/** Backslash-escape the characters that would make text into Markdown. */
export function escapeMarkdown(text: string): string {
  return text.replace(/\s+/g, ' ').trim().replace(/[\\`*_[\]<>|]/g, '\\$&');
}

/**
 * "7.5 of 9 must-haves covered". Covered counts strong as 1 and partial as
 * ½, so it is always a whole or a half: shown as an integer, or with one
 * decimal. Singular for one must-have; a plain sentence for none.
 */
export function coverageLine(coverage: NonNullable<FitReport['coverage']>): string {
  if (coverage.mustHaves === 0) return 'No must-haves could be assessed.';
  const covered = Number.isInteger(coverage.covered) ? String(coverage.covered) : coverage.covered.toFixed(1);
  const noun = coverage.mustHaves === 1 ? 'must-have' : 'must-haves';
  return `${covered} of ${coverage.mustHaves} ${noun} covered`;
}

function rowLines(row: Requirement, byId: ReadonlyMap<string, Evidence>): string[] {
  const lines = [
    `- **${VERDICT_LABELS[row.verdict]}**: ${escapeMarkdown(row.text)}`,
    `  ${escapeMarkdown(row.note)}`,
  ];
  for (const id of row.evidenceIds) {
    const evidence = byId.get(id);
    if (!evidence) continue;
    const label = escapeMarkdown(`${evidenceLabel(evidence)} (${entryLabel(evidence.entry)})`);
    lines.push(`  - ${label}: [${escapeMarkdown(evidence.source.label)}](${evidence.source.href})`);
  }
  return lines;
}

function section(title: string, rows: readonly Requirement[], byId: ReadonlyMap<string, Evidence>): string[] {
  if (rows.length === 0) return [];
  return [`## ${title}`, '', ...rows.flatMap((row) => rowLines(row, byId)), ''];
}

/** Said in place of a coverage line when `coverage` is null. */
export const NO_COVERAGE_LINE =
  "No coverage score: the must-haves couldn't be identified, or most of them are outside what my portfolio can show either way.";

/**
 * Both modes group rows as the UI does: Must-have, Nice-to-have, then Not
 * assessed (whatever its priority). They differ only in the lead: model
 * mode says a model chose the requirements; the no-model path leads with
 * SCAN_DISCLAIMER.
 */
export function reportToMarkdown(report: FitReport, corpus: Corpus = CORPUS): string {
  const byId = new Map(corpus.evidence.map((e) => [e.id, e]));
  const rows = report.requirements;
  const lines = [`# Fit report: ${escapeMarkdown(report.role)}`, ''];

  lines.push(
    report.mode === 'model'
      ? `Checked against ${corpus.profile.name}'s portfolio. A model picked the requirements from the job description's lines; the verdicts are computed from the evidence below, not generated.`
      : `Checked against ${corpus.profile.name}'s portfolio. ${SCAN_DISCLAIMER} The verdicts are computed from the evidence below.`,
    '',
  );
  lines.push(
    report.coverage
      ? `**${coverageLine(report.coverage)}** (strong counts 1, partial counts ½; not-assessed rows are left out)`
      : NO_COVERAGE_LINE,
    '',
  );
  const level = levelLine(report.role);
  if (level) lines.push(escapeMarkdown(level), '');
  const assessed = rows.filter((r) => r.verdict !== 'not_assessed');
  lines.push(
    ...section('Must-have', assessed.filter((r) => r.priority === 'must'), byId),
    ...section('Nice-to-have', assessed.filter((r) => r.priority === 'nice'), byId),
    ...section('Not assessed', rows.filter((r) => r.verdict === 'not_assessed'), byId),
  );
  if (rows.length === 0) lines.push('No requirements were found in this job description.', '');

  lines.push(`Generated by the fit checker at ${corpus.profile.links.site}/fit`);
  return lines.join('\n') + '\n';
}
