import { describe, expect, it } from 'vitest';

import { CORPUS } from '@/data/corpus';
import type { FitReport } from '@/lib/fit/contract';
import { judge } from '@/lib/fit/judge';
import { coverageLine, escapeMarkdown, reportToMarkdown } from '@/lib/fit/markdown';
import { SCAN_DISCLAIMER, scanJd } from '@/lib/fit/scan';

const NOW = new Date('2026-09-23T12:00:00Z');

describe('coverageLine', () => {
  it.each([
    [{ covered: 7.5, mustHaves: 9 }, '7.5 of 9 must-haves covered'],
    [{ covered: 7, mustHaves: 9 }, '7 of 9 must-haves covered'],
    [{ covered: 0, mustHaves: 3 }, '0 of 3 must-haves covered'],
    [{ covered: 0.5, mustHaves: 1 }, '0.5 of 1 must-have covered'],
    [{ covered: 1, mustHaves: 1 }, '1 of 1 must-have covered'],
    [{ covered: 0, mustHaves: 0 }, 'No must-haves could be assessed.'],
  ])('%o → %s', (coverage, line) => {
    expect(coverageLine(coverage)).toBe(line);
  });
});

describe('escapeMarkdown', () => {
  it('neutralises links, emphasis, code and HTML and flattens newlines', () => {
    expect(escapeMarkdown('[click](https://evil.example) *now* `x` <b>|\n# heading')).toBe(
      '\\[click\\](https://evil.example) \\*now\\* \\`x\\` \\<b\\>\\| # heading',
    );
  });
});

describe('reportToMarkdown', () => {
  const report = judge(
    {
      role: 'Senior [Frontend](https://evil.example) Engineer',
      requirements: [
        { text: 'Accessibility', priority: 'must', skills: ['wcag'], otherSkills: [], minYears: null },
        { text: 'Kafka', priority: 'must', skills: [], otherSkills: ['Kafka'], minYears: null },
        { text: 'Node.js', priority: 'nice', skills: ['node-js'], otherSkills: [], minYears: null },
        { text: 'Communication', priority: 'must', skills: [], otherSkills: [], minYears: null },
      ],
    },
    CORPUS,
    NOW,
  );

  it('renders the model-mode report', () => {
    expect(reportToMarkdown(report)).toMatchInlineSnapshot(`
      "# Fit report: Senior \\[Frontend\\](https://evil.example) Engineer

      Checked against Kaleb Kougl's portfolio. A model extracted the requirements; the verdicts are computed from the evidence below, not generated.

      **1 of 2 must-haves covered** (strong counts 1, partial counts ½; not-assessed rows are left out)

      ## Must-have

      - **Strong**: Accessibility
        Evidence: WCAG across 20+ React components (Indeed).
        - WCAG across 20+ React components (Indeed): [Résumé: Software Engineer II, Indeed.com](https://kalebkougl-portfolio.vercel.app/#career)
      - **Gap**: Kafka
        Not in my work yet.

      ## Nice-to-have

      - **Partial**: Node.js
        Evidence: Node.js video upload pipeline (IBM).
        - Node.js video upload pipeline (IBM): [Résumé: Software Engineer II, IBM](https://kalebkougl-portfolio.vercel.app/#career)

      ## Not assessed

      - **Not assessed**: Communication
        Not something my portfolio shows either way.

      Generated by the fit checker at https://kalebkougl-portfolio.vercel.app/fit
      "
    `);
  });

  it('links every evidence record to its source', () => {
    const md = reportToMarkdown(report);
    for (const row of report.requirements) {
      for (const id of row.evidenceIds) {
        const evidence = CORPUS.evidence.find((e) => e.id === id)!;
        expect(md).toContain(`](${evidence.source.href})`);
      }
    }
  });

  it('renders scan mode without coverage, grouped by found / not found', () => {
    const md = reportToMarkdown(scanJd('Staff Engineer\nReact and Go.', CORPUS, NOW));
    expect(md).toContain(SCAN_DISCLAIMER);
    expect(SCAN_DISCLAIMER).toMatch(/^Keyword scan: recognises engineering terms only/);
    expect(md).not.toContain('must-haves covered');
    expect(md.indexOf('## In my work')).toBeLessThan(md.indexOf('## Not in my work'));
    expect(md).toContain('- **Gap**: Go');
  });

  it('says so when a scan finds nothing', () => {
    const md = reportToMarkdown(scanJd('Barista\nMust love coffee.', CORPUS, NOW));
    expect(md).toContain('No skills from my vocabulary were mentioned.');
  });

  it('skips evidence ids the corpus does not know rather than inventing a link', () => {
    const tampered: FitReport = {
      ...report,
      requirements: [{ ...report.requirements[0], evidenceIds: ['nope.nope'] }],
    };
    expect(reportToMarkdown(tampered)).not.toContain('nope.nope');
  });
});
